services:
  - type: web
    name: dragonfly-bot
    env: python
    region: frankfurt            # ← فرانکفورت
    plan: free
    buildCommand: bash .render/build.sh
    startCommand: python main.py
    autoDeploy: true

