services:
  - type: web
    name: dragonfly-bot
    env: python
    plan: free
    buildCommand: >-
      pip install --upgrade pip wheel setuptools &&
      pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
