services:
  - type: web
    name: dragonfly-bot
    env: python
    pythonVersion: "3.11.0"
    region: frankfurt
    plan: free
    buildCommand: |
      pip install --upgrade pip setuptools wheel &&
      pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    port: null                     # ← این خط کل مشکل رو حل می‌کنه!



